# Generated by Django 3.2.8 on 2023-10-28 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('source', models.CharField(max_length=100, verbose_name='来源')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期')),
                ('content', models.TextField(verbose_name='内容')),
            ],
        ),
    ]
